//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 11:42:37 PM IST 
//


package com.hightail.yahoo.weather.entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rss }
     * 
     */
    public Rss createRss() {
        return new Rss();
    }

    /**
     * Create an instance of {@link Rss.Channel }
     * 
     */
    public Rss.Channel createRssChannel() {
        return new Rss.Channel();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item }
     * 
     */
    public Rss.Channel.Item createRssChannelItem() {
        return new Rss.Channel.Item();
    }

    /**
     * Create an instance of {@link Rss.Channel.Location }
     * 
     */
    public Rss.Channel.Location createRssChannelLocation() {
        return new Rss.Channel.Location();
    }

    /**
     * Create an instance of {@link Rss.Channel.Units }
     * 
     */
    public Rss.Channel.Units createRssChannelUnits() {
        return new Rss.Channel.Units();
    }

    /**
     * Create an instance of {@link Rss.Channel.Wind }
     * 
     */
    public Rss.Channel.Wind createRssChannelWind() {
        return new Rss.Channel.Wind();
    }

    /**
     * Create an instance of {@link Rss.Channel.Atmosphere }
     * 
     */
    public Rss.Channel.Atmosphere createRssChannelAtmosphere() {
        return new Rss.Channel.Atmosphere();
    }

    /**
     * Create an instance of {@link Rss.Channel.Astronomy }
     * 
     */
    public Rss.Channel.Astronomy createRssChannelAstronomy() {
        return new Rss.Channel.Astronomy();
    }

    /**
     * Create an instance of {@link Rss.Channel.Image }
     * 
     */
    public Rss.Channel.Image createRssChannelImage() {
        return new Rss.Channel.Image();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Condition }
     * 
     */
    public Rss.Channel.Item.Condition createRssChannelItemCondition() {
        return new Rss.Channel.Item.Condition();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Forecast }
     * 
     */
    public Rss.Channel.Item.Forecast createRssChannelItemForecast() {
        return new Rss.Channel.Item.Forecast();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Guid }
     * 
     */
    public Rss.Channel.Item.Guid createRssChannelItemGuid() {
        return new Rss.Channel.Item.Guid();
    }

}
