//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 11:42:37 PM IST 
//


package com.hightail.yahoo.weather.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ttl" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="units">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="temperature" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="wind">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="chill" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="atmosphere">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="humidity" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="rising" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="astronomy">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="sunrise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="sunset" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="image">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="item">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="condition">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="temp" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="forecast">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="day" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                     &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="guid">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel"
})
@XmlRootElement(name = "rss")
public class Rss {

    @XmlElement(required = true)
    protected Channel channel;
    @XmlAttribute(name = "version")
    protected BigDecimal version;

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link com.hightail.yahoo.weather.entities.Rss.Channel }
     *     
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.hightail.yahoo.weather.entities.Rss.Channel }
     *     
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ttl" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="units">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="temperature" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="wind">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="chill" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="atmosphere">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="humidity" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="rising" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="astronomy">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="sunrise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="sunset" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="image">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="item">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="condition">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="temp" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="forecast">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="day" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                           &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="guid">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "link",
        "description",
        "language",
        "lastBuildDate",
        "ttl",
        "location",
        "units",
        "wind",
        "atmosphere",
        "astronomy",
        "image",
        "item"
    })
    public static class Channel {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String link;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String language;
        @XmlElement(required = true)
        protected String lastBuildDate;
        protected int ttl;
        @XmlElement(required = true)
        protected Location location;
        @XmlElement(required = true)
        protected Units units;
        @XmlElement(required = true)
        protected Wind wind;
        @XmlElement(required = true)
        protected Atmosphere atmosphere;
        @XmlElement(required = true)
        protected Astronomy astronomy;
        @XmlElement(required = true)
        protected Image image;
        @XmlElement(required = true)
        protected Item item;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the lastBuildDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastBuildDate() {
            return lastBuildDate;
        }

        /**
         * Sets the value of the lastBuildDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastBuildDate(String value) {
            this.lastBuildDate = value;
        }

        /**
         * Gets the value of the ttl property.
         * 
         */
        public int getTtl() {
            return ttl;
        }

        /**
         * Sets the value of the ttl property.
         * 
         */
        public void setTtl(int value) {
            this.ttl = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Location }
         *     
         */
        public Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Location }
         *     
         */
        public void setLocation(Location value) {
            this.location = value;
        }

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Units }
         *     
         */
        public Units getUnits() {
            return units;
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Units }
         *     
         */
        public void setUnits(Units value) {
            this.units = value;
        }

        /**
         * Gets the value of the wind property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Wind }
         *     
         */
        public Wind getWind() {
            return wind;
        }

        /**
         * Sets the value of the wind property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Wind }
         *     
         */
        public void setWind(Wind value) {
            this.wind = value;
        }

        /**
         * Gets the value of the atmosphere property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Atmosphere }
         *     
         */
        public Atmosphere getAtmosphere() {
            return atmosphere;
        }

        /**
         * Sets the value of the atmosphere property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Atmosphere }
         *     
         */
        public void setAtmosphere(Atmosphere value) {
            this.atmosphere = value;
        }

        /**
         * Gets the value of the astronomy property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Astronomy }
         *     
         */
        public Astronomy getAstronomy() {
            return astronomy;
        }

        /**
         * Sets the value of the astronomy property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Astronomy }
         *     
         */
        public void setAstronomy(Astronomy value) {
            this.astronomy = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Image }
         *     
         */
        public Image getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Image }
         *     
         */
        public void setImage(Image value) {
            this.image = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item }
         *     
         */
        public Item getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item }
         *     
         */
        public void setItem(Item value) {
            this.item = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="sunrise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="sunset" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Astronomy {

            @XmlAttribute(name = "sunrise")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar sunrise;
            @XmlAttribute(name = "sunset")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar sunset;

            /**
             * Gets the value of the sunrise property.
             * 
             * @return
             *     possible object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getSunrise() {
                return sunrise;
            }

            /**
             * Sets the value of the sunrise property.
             * 
             * @param value
             *     allowed object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public void setSunrise(XMLGregorianCalendar value) {
                this.sunrise = value;
            }

            /**
             * Gets the value of the sunset property.
             * 
             * @return
             *     possible object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getSunset() {
                return sunset;
            }

            /**
             * Sets the value of the sunset property.
             * 
             * @param value
             *     allowed object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public void setSunset(XMLGregorianCalendar value) {
                this.sunset = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="humidity" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="visibility" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="rising" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Atmosphere {

            @XmlAttribute(name = "humidity")
            protected Integer humidity;
            @XmlAttribute(name = "visibility")
            protected Integer visibility;
            @XmlAttribute(name = "pressure")
            protected BigDecimal pressure;
            @XmlAttribute(name = "rising")
            protected Integer rising;

            /**
             * Gets the value of the humidity property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHumidity() {
                return humidity;
            }

            /**
             * Sets the value of the humidity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHumidity(Integer value) {
                this.humidity = value;
            }

            /**
             * Gets the value of the visibility property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getVisibility() {
                return visibility;
            }

            /**
             * Sets the value of the visibility property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setVisibility(Integer value) {
                this.visibility = value;
            }

            /**
             * Gets the value of the pressure property.
             * 
             * @return
             *     possible object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public BigDecimal getPressure() {
                return pressure;
            }

            /**
             * Sets the value of the pressure property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public void setPressure(BigDecimal value) {
                this.pressure = value;
            }

            /**
             * Gets the value of the rising property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRising() {
                return rising;
            }

            /**
             * Sets the value of the rising property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRising(Integer value) {
                this.rising = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "width",
            "height",
            "link",
            "url"
        })
        public static class Image {

            @XmlElement(required = true)
            protected String title;
            protected int width;
            protected int height;
            @XmlElement(required = true)
            protected String link;
            @XmlElement(required = true)
            protected String url;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public int getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(int value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public int getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(int value) {
                this.height = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="condition">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="temp" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="forecast">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="day" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                 &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="guid">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "lat",
            "_long",
            "link",
            "pubDate",
            "condition",
            "description",
            "forecast",
            "guid"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected BigDecimal lat;
            @XmlElement(name = "long", required = true)
            protected BigDecimal _long;
            @XmlElement(required = true)
            protected String link;
            @XmlElement(required = true)
            protected String pubDate;
            @XmlElement(required = true)
            protected Condition condition;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected Forecast forecast;
            @XmlElement(required = true)
            protected Guid guid;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the lat property.
             * 
             * @return
             *     possible object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public BigDecimal getLat() {
                return lat;
            }

            /**
             * Sets the value of the lat property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public void setLat(BigDecimal value) {
                this.lat = value;
            }

            /**
             * Gets the value of the long property.
             * 
             * @return
             *     possible object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public BigDecimal getLong() {
                return _long;
            }

            /**
             * Sets the value of the long property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.math.BigDecimal }
             *     
             */
            public void setLong(BigDecimal value) {
                this._long = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the pubDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPubDate() {
                return pubDate;
            }

            /**
             * Sets the value of the pubDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPubDate(String value) {
                this.pubDate = value;
            }

            /**
             * Gets the value of the condition property.
             * 
             * @return
             *     possible object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Condition }
             *     
             */
            public Condition getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Condition }
             *     
             */
            public void setCondition(Condition value) {
                this.condition = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the forecast property.
             * 
             * @return
             *     possible object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Forecast }
             *     
             */
            public Forecast getForecast() {
                return forecast;
            }

            /**
             * Sets the value of the forecast property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Forecast }
             *     
             */
            public void setForecast(Forecast value) {
                this.forecast = value;
            }

            /**
             * Gets the value of the guid property.
             * 
             * @return
             *     possible object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Guid }
             *     
             */
            public Guid getGuid() {
                return guid;
            }

            /**
             * Sets the value of the guid property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.hightail.yahoo.weather.entities.Rss.Channel.Item.Guid }
             *     
             */
            public void setGuid(Guid value) {
                this.guid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="temp" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Condition {

                @XmlAttribute(name = "text")
                protected String text;
                @XmlAttribute(name = "code")
                protected Integer code;
                @XmlAttribute(name = "temp")
                protected Integer temp;
                @XmlAttribute(name = "date")
                protected String date;

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setCode(Integer value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the temp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTemp() {
                    return temp;
                }

                /**
                 * Sets the value of the temp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTemp(Integer value) {
                    this.temp = value;
                }

                /**
                 * Gets the value of the date property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDate() {
                    return date;
                }

                /**
                 * Sets the value of the date property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDate(String value) {
                    this.date = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="day" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *       &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Forecast {

                @XmlAttribute(name = "day")
                protected String day;
                @XmlAttribute(name = "date")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar date;
                @XmlAttribute(name = "low")
                protected Integer low;
                @XmlAttribute(name = "high")
                protected Integer high;
                @XmlAttribute(name = "text")
                protected String text;
                @XmlAttribute(name = "code")
                protected Integer code;

                /**
                 * Gets the value of the day property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDay() {
                    return day;
                }

                /**
                 * Sets the value of the day property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDay(String value) {
                    this.day = value;
                }

                /**
                 * Gets the value of the date property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link javax.xml.datatype.XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDate() {
                    return date;
                }

                /**
                 * Sets the value of the date property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link javax.xml.datatype.XMLGregorianCalendar }
                 *     
                 */
                public void setDate(XMLGregorianCalendar value) {
                    this.date = value;
                }

                /**
                 * Gets the value of the low property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getLow() {
                    return low;
                }

                /**
                 * Sets the value of the low property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setLow(Integer value) {
                    this.low = value;
                }

                /**
                 * Gets the value of the high property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getHigh() {
                    return high;
                }

                /**
                 * Sets the value of the high property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setHigh(Integer value) {
                    this.high = value;
                }

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setCode(Integer value) {
                    this.code = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Guid {

                @XmlAttribute(name = "isPermaLink")
                protected Boolean isPermaLink;

                /**
                 * Gets the value of the isPermaLink property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isIsPermaLink() {
                    return isPermaLink;
                }

                /**
                 * Sets the value of the isPermaLink property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setIsPermaLink(Boolean value) {
                    this.isPermaLink = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Location {

            @XmlAttribute(name = "city")
            protected String city;
            @XmlAttribute(name = "region")
            protected String region;
            @XmlAttribute(name = "country")
            protected String country;

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the region property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegion() {
                return region;
            }

            /**
             * Sets the value of the region property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegion(String value) {
                this.region = value;
            }

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="temperature" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="pressure" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Units {

            @XmlAttribute(name = "temperature")
            protected String temperature;
            @XmlAttribute(name = "distance")
            protected String distance;
            @XmlAttribute(name = "pressure")
            protected String pressure;
            @XmlAttribute(name = "speed")
            protected String speed;

            /**
             * Gets the value of the temperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTemperature() {
                return temperature;
            }

            /**
             * Sets the value of the temperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTemperature(String value) {
                this.temperature = value;
            }

            /**
             * Gets the value of the distance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDistance() {
                return distance;
            }

            /**
             * Sets the value of the distance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDistance(String value) {
                this.distance = value;
            }

            /**
             * Gets the value of the pressure property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPressure() {
                return pressure;
            }

            /**
             * Sets the value of the pressure property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPressure(String value) {
                this.pressure = value;
            }

            /**
             * Gets the value of the speed property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpeed() {
                return speed;
            }

            /**
             * Sets the value of the speed property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpeed(String value) {
                this.speed = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="chill" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Wind {

            @XmlAttribute(name = "chill")
            protected Integer chill;
            @XmlAttribute(name = "direction")
            protected Integer direction;
            @XmlAttribute(name = "speed")
            protected Integer speed;

            /**
             * Gets the value of the chill property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getChill() {
                return chill;
            }

            /**
             * Sets the value of the chill property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setChill(Integer value) {
                this.chill = value;
            }

            /**
             * Gets the value of the direction property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDirection() {
                return direction;
            }

            /**
             * Sets the value of the direction property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDirection(Integer value) {
                this.direction = value;
            }

            /**
             * Gets the value of the speed property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getSpeed() {
                return speed;
            }

            /**
             * Sets the value of the speed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSpeed(Integer value) {
                this.speed = value;
            }

        }

    }

}
